### ISSUE TITLE
the company is still hiring?

### ISSUE THREAD

**Issue by aj07mm** [thinkcompany/code-challenges#29]

**Comment by zhdlispd** [comment]
have you asked your recruiter? got no response.

**Comment by tjnicolaides** [comment]
The position is still open. We're hiring 4 more JS application developers. Thanks!

**Comment by zhdlispd** [comment]
Thanks!
How do I submit my resume?

**Comment by tjnicolaides** [comment]
The listing is here: http://tbi.applytojob.com/apply/ezEwut/Web-Developer-Contract

Looking forward to your pull request on this repository. Thanks!

**Comment by zhdlispd** [comment]
Thanks!
In fact, I have sent you my pull request and my project is temporarily
placed on my company's AWS.
I put the link in my pull-request comment:
http://ec2-54-175-242-254.compute-1.amazonaws.com/?email=zhdlispd@gmail.com&lk=5042515959&sk=7581

I will send you my resume later today.

Chen
